DROP TABLE IF EXISTS TOKEN_STATUS;

CREATE TABLE TOKEN_DETAIL (
  key_value VARCHAR(250)  PRIMARY KEY,
  start_time TIMESTAMP,
  usage_limit INT NOT NULL
);

DROP TABLE IF EXISTS WEATHER_HOURLY_DATA;

CREATE TABLE WEATHER_DATA (
  city_name VARCHAR(250),
  country_code VARCHAR(250),
  weather_desc VARCHAR(500),
  CONSTRAINT UC UNIQUE (city_name, country_code)
);