DROP TABLE IF EXISTS TOKEN_STATUS;

CREATE TABLE TOKEN_STATUS (
  key_name VARCHAR(250)  PRIMARY KEY,
  timestamp TIMESTAMP,
  usage VARCHAR(250) NOT NULL,
);

DROP TABLE IF EXISTS WEATHER_HOURLY_DATA;

CREATE TABLE WEATHER_HOURLY_DATA (
  city_name VARCHAR(250)  PRIMARY KEY,
  country_code VARCHAR(250)  PRIMARY KEY,
  weather_desc VARCHAR(500),
  CONSTRAINT PRIMARY KEY (city_name, country_code),
);